# mapa.py

MAPA_TEXTO = [
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "GGPPPPPPPPPPPPPPGGGGPPPPPAGGGGGGGGGGGGGGGG",
    "GGPEEEEEPEEEEEEPGGGGPEEEGAGGGPPPPPPPPPPPGG",
    "GGPEEEEEPEEEEEEPPPPPPEEAAAGGGPGGGGGGGGGPGG",
    "GGPEEPEEPEEEPEEPEEEEGEEAAAGGGPGGGTTTGGGPGG",
    "GGPPPPPPPPPPPPPPPEEEGEEEGAGGGPGGGTTTGGGPGG",
    "GGPTTTTTTTTTTTTPPEEEGGGGGAGGGPGGGTTTGGGPGG",
    "GGPTTTTTTTTTTTTPEEEEGEEEGAGGGPGGGTTTGGGPGG",
    "GGPTTTTGGGGTTTTPPPPPPEEEGAGGGPGGGGGGGGGPGG",
    "GGPTTTTGGGGTTTTPGGGGPEEAAAGGGPPPPPPPPPPPGG",
]
